repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.57.0
          - eslint-config-prettier@9.1.0
        files: \.(js|ts|jsx|tsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.1
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|html|css|md)$

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: [-r, backend]

  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety
        language: system
        args: [check, --json]
        files: pyproject.toml$